"use client";
import { useState } from "react";
import marketScan from "../public/data/market-scan.json";

type View="scan"|"opportunities"|"card"|"player"|"portfolio"|"research";
const nav:[View,string][]=[["scan","Market Scan"],["opportunities","Opportunities"],["card","Card Intelligence"],["player","Player Market"],["portfolio","Portfolio"],["research","Research"]];
const money=new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0});
const signals=marketScan.items.flatMap(item=>item.action?[{signal:item.action,tag:item.alerts[0]??"—",sport:item.sport,card:item.card,price:item.fair_value===null?"Not enough evidence":money.format(item.fair_value),move:`${item.move_30d>=0?"+":""}${(item.move_30d*100).toFixed(1)}%`,evidence:item.evidence_grade,confidence:item.confidence,why:item.thesis}]:[]);
const scanTime=new Intl.DateTimeFormat("en-US",{month:"short",day:"numeric",hour:"numeric",minute:"2-digit",timeZone:"America/Phoenix",timeZoneName:"short"}).format(new Date(marketScan.generated_at));
const metrics=[[["Fair value","$4,820"],["30 days","+8.4%"],["90 days","+18.7%"]],[["Sales velocity","↑ 34%"],["Liquidity","81 / 100"],["Evidence","A"]],[["Player hierarchy","#3"],["Signal","ACCUMULATE"],["Confidence","86%"]]];

export default function Home(){const [view,setView]=useState<View>("scan");const [sport,setSport]=useState("All sports");return <div className="shell">
 <aside><div className="logo"><span>OS</span><div><b>Market OS</b><small>SPORTS CARD INTELLIGENCE</small></div></div><div className="nav-label">COMMAND CENTER</div>{nav.map(([id,label])=><button key={id} onClick={()=>setView(id)} className={view===id?"active":""}><i>{id==="scan"?"⌁":id==="opportunities"?"⚡":id==="card"?"▣":id==="player"?"◎":id==="portfolio"?"◫":"≡"}</i>{label}</button>)}<div className="system"><span></span><div><b>MARKET ONLINE</b><small>Last scan 4 min ago</small></div></div></aside>
 <main><header><div className="search">⌕ <input aria-label="Search cards or players" placeholder="Search any card, player, set…"/></div><div className="data-state" title={marketScan.source.label}>ILLUSTRATIVE ALPHA DATA</div><button className="scan-btn" onClick={()=>setView("scan")}>Run market scan</button><div className="avatar">SL</div></header>
 {view==="scan"&&<><div className="page-head"><div><span className="kicker">MARKET COMMAND CENTER</span><h1>Market Scan</h1><p>Material changes across the monitored universe. Noise removed.</p></div><div className="asof">AS OF {scanTime.toUpperCase()}<br/><b>{marketScan.universe_size} cards monitored</b></div></div><div className="tape"><div><span>MARKET PULSE</span><b>Selective strength</b></div><div><span>24H SIGNAL CHANGES</span><b className="green">12 strengthened</b></div><div><span>EVIDENCE HEALTH</span><b>84% investable</b></div><div><span>CAPITAL POSTURE</span><b>Patiently offensive</b></div></div><div className="toolbar"><div>{["All signals","BUY","ACCUMULATE","HOLD","TRIM","SELL"].map(x=><button className={x==="All signals"?"on":""} key={x}>{x}</button>)}</div><select value={sport} onChange={e=>setSport(e.target.value)}><option>All sports</option><option>NBA</option><option>MLB</option><option>NFL</option></select></div><section className="signal-table"><div className="table-title"><b>Highest-conviction changes</b><span>Ranked by signal strength × evidence quality</span></div><div className="thead"><span>SIGNAL</span><span>ASSET</span><span>FAIR VALUE</span><span>30D</span><span>EVIDENCE</span><span>CONF.</span></div>{signals.filter(x=>sport==="All sports"||x.sport===sport).map((s,i)=><button className="row" key={s.card} onClick={()=>setView("card")}><span><b className={`pill ${s.signal.toLowerCase()}`}>{s.signal}</b><small>{s.tag}</small></span><span><b>{s.card}</b><small>{s.sport} · Hierarchy #{i+2}</small></span><b>{s.price}</b><b className={s.move.startsWith("+")?"green":"red"}>{s.move}</b><b className="evidence">{s.evidence}</b><b>{s.confidence}%</b></button>)}</section></>}
 {view==="opportunities"&&<><div className="page-head"><div><span className="kicker">PROACTIVE DISCOVERY</span><h1>Opportunity Feed</h1><p>The system tells you where the market may be wrong—and why.</p></div></div><div className="op-grid">{signals.slice(0,3).map((s,i)=><article className="op" key={s.card}><div className="op-top"><b>{s.tag} · {s.sport}</b><span>{s.confidence}% confidence</span></div><h2>{i===0?"Potential grail compression":i===1?"Premium rookie dislocation":"Supply expansion warning"}</h2><h3>{s.card}</h3><div className="drivers"><span><small>SALES VELOCITY</small><b>{i===0?"+34%":"+18%"}</b></span><span><small>LISTINGS</small><b>{i===2?"+29%":"−19%"}</b></span><span><small>SUPERIOR TIER</small><b>+41%</b></span></div><p>{s.why}</p><div className="action"><span>ACTION</span><b>{s.signal} below {i===0?"$4,650":"$3,050"}</b></div></article>)}</div></>}
 {view==="card"&&<><div className="crumb">Market Scan / NBA / Stephen Curry</div><div className="card-hero"><div><span className="kicker">CARD INTELLIGENCE</span><h1>2009 Topps Chrome Stephen Curry</h1><p>#101 · Rookie · PSA 9</p></div><div><b className="pill accumulate">ACCUMULATE</b><small>86% confidence · Evidence A</small></div></div><div className="metric-groups">{metrics.map((group,i)=><div key={i}>{group.map(([k,v])=><span key={k}><small>{k}</small><b className={v.startsWith("+")?"green":""}>{v}</b></span>)}</div>)}</div><div className="levels"><div><small>IDEAL ENTRY</small><b>&lt; $4,650</b></div><div><small>DO NOT CHASE</small><b>&gt; $5,200</b></div><div><small>BULL / BASE / BEAR</small><b>$6,400 / $5,350 / $3,900</b></div></div><section className="thesis"><div><h2>Why the market may be wrong</h2><p>Premium Curry rookie demand is moving up the hierarchy faster than this tier is repricing. Accepted sales velocity increased 34% while active listings declined 19%. The superior grail tier advanced 41% over 90 days; this card advanced 18.7%, leaving measurable compression potential.</p><h3>Invalidation</h3><p>Exit the thesis if 30-day sales velocity falls below baseline, active supply expands more than 20%, or accepted sales break below $4,050.</p></div><aside><span>12 accepted sales</span><span>2 excluded comps</span><span>Latest sale 3 days ago</span><span>Dispersion 6.1%</span></aside></section></>}
 {view==="player"&&<><div className="page-head"><div><span className="kicker">PLAYER MARKET</span><h1>Stephen Curry</h1><p>Where value, liquidity, and hierarchy are moving across the player market.</p></div></div><div className="player-summary"><div><small>PLAYER MARKET VALUE</small><b>+12.8%</b><span>90 days</span></div><div><small>STRONGEST SEGMENT</small><b>Premium rookies</b><span>velocity +27%</span></div><div><small>CURRENT MISPRICING</small><b>Topps Chrome PSA 9</b><span>grail compression</span></div></div><section className="hierarchy"><h2>Rookie hierarchy</h2>{["National Treasures RPA /99","Topps Chrome Refractor","Topps Chrome Base","Panini Prestige #157"].map((x,i)=><div key={x}><b>#{i+1}</b><span><strong>{x}</strong><small>{i===0?"Long-term grail":i===1?"Best $10k expression":i===2?"Best $5k expression":"Best $500 expression"}</small></span><span className={i===2?"green":""}>{i===2?"ACCUMULATE":"HOLD"}</span><strong>{["$184k","$32.4k","$4.82k","$640"][i]}</strong></div>)}</section></>}
 {view==="portfolio"&&<><div className="page-head"><div><span className="kicker">CAPITAL ALLOCATOR</span><h1>Deploy $5,000</h1><p>Best risk-adjusted action across fresh capital and current holdings.</p></div></div><div className="allocation"><article><span className="rank">01</span><div><b>Buy Curry Topps Chrome PSA 9</b><p>Maximum entry $4,650 · 6–18 month hold</p></div><strong>70% · $3,500</strong></article><article><span className="rank">02</span><div><b>Keep cash available</b><p>Wait for evidence-confirmed dislocations</p></div><strong>30% · $1,500</strong></article><div className="no-action"><b>No forced deployment</b><p>The allocator preserves cash when no opportunity clears its evidence and return hurdles.</p></div></div></>}
 {view==="research"&&<><div className="page-head"><div><span className="kicker">MARKET INTELLIGENCE</span><h1>Research Desk</h1><p>Why markets moved, what could happen next, and which cards express it best.</p></div></div><div className="research-grid">{[["ATHLETE CATALYST","Curry extension and title-window repricing","Collector demand is rotating toward premium rookies as long-term career certainty increases."],["MARKET STRUCTURE","Grail compression is widening","Superior Curry tiers moved 2.2× faster than liquid substitutes over 90 days."],["SUPPLY WATCH","Modern PSA 10 population pressure","Select 2020–23 silver parallels show supply growth outpacing buyer absorption."],["AUCTION BEHAVIOR","High-end bidding depth improves","Three consecutive premium lots cleared above estimate with broader bidder participation."]].map(([tag,title,body])=><article key={title}><span>{tag}</span><h2>{title}</h2><p>{body}</p><button>Open research note →</button></article>)}</div></>}
 </main></div>}
